#!/bin/sh
set -euf

##
# This script removes datestamped files.
#
# This deletes files with names that end in a separator then ISO date:
#
#   * Example: foo-2017-12-31, foo_2017_12_31, etc.
#
# Syntax:
# 
#     rm-datestamped-files [dir]
# 
# Example to do the current directory:
# 
#     rm-datestamped-files
# 
# Example to do a specific directory:
#
#     rm-datestamped-files /foo/goo
#
# The file name separator can be a period, dash, or underscore.
#
#
# ## Compatibility notes:
#
# We prefer to be more compatible rather than system-specific.
#
#   * To delete files, we prefer `-exec rm` vs. `-delete`.
#     The former is more compatible, the latter is faster.
#
#   * To regex match, we prefer patterns to be basic vs. extended.
#     The former is more compatible, the latter is more modern.
#
#   * We prefer POSIX code vs. shell-specific code.
#
#
# ## Tracking
# 
#   * Command: rm-datestamped-files
#   * Version: 3.0.0
#   * Created: 2013-12-09
#   * Updated: 2017-08-29
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##

find "${1:-.}" -regex ".*[-_\.][0123456789][0123456789][0123456789][0123456789][-_\.][0123456789][0123456789][-_\.][0123456789][0123456789]" -type f -exec rm {} \;
